MOCK_RESPONSE = {
    "seoTitle": "de vente et viager d'appartements ou de maisons à Paris",
    "classifiedsData": {
        "count": 9381,
        "geoLocalizedCount": 6689,
        "classifieds": [
            {
                "id": 140321175,
                "publicationId": 534193,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 19,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/x/j/4/1xj47g1pq74778177b2l7rm3gya3tzpn5mr37vlz4.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/8/y/t/28yte2bo7nfdyy9cnovlk3ul6u0y7jy3feqz8lon4.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/c/9/b/1c9bfw5ceqdf3h4uh3bvah1j5f8ykti6gch34olq8.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/4/w/v/04wv8qeb242y0gsu5vj18k9k76j8a213fy5nhaxa8.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/m/a/8/1ma877rrajocu6m1njh6yp3l19gchd7p6yusl6bcw.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "27\u00A0391 €",
                    "rawPrice": "6300000.0",
                    "priceNote": None,
                    "price": "6\u00A0300\u00A0000 €",
                    "monthlyPrice": 25969,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 108728,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-17eme-75/agency-81416.htm",
                    "contactName": "Paris Ouest Sotheby's IR - Paris 17ème",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/0/i/x/z/0ixz2uiul728zvuihqo2d52dly4g3ayo88ofmnz94.jpg",
                    "phoneNumber": "0146222727",
                    "email": "true",
                    "agencyLink": "http://www.parisouest-sothebysrealty.com",
                },
                "tags": ["5 p", "1 ch", "230 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75116",
                "isExclusive": False,
                "cityLabel": "Paris 16ème",
                "districtLabel": "Chaillot",
                "zipCode": "75116",
                "description": "Paris 16ème - Palais de Tokyo. Rare. Vue Tour Eiffel et 360+ sur Paris, superbe penthouse de 230 m² avec 300 m² de terrasse. ",
                "videoURL": None,
                "virtualVisitURL": "https://www.youtube.com/embed/D1eHnk0na6Y",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-16eme-75/chaillot/140321175/",
                "optionalCriteria": [],
            },
            {
                "id": 146441595,
                "publicationId": 720813,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 7,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/2/8/l/g/28lg15q1o3ijc1r93viz8p3d5ioh8n589lht1ss9q.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/t/c/k/0tckar0assij7apkngx9raxosf12l1z5wdh4o8hlr.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/v/c/8/1vc84izv8h9g79v9ity63p1a3rlj3gl2ubrtggrhb.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/6/h/5/16h5u4fhtvc0309n8dqiiemdke46bc0lyf6xakb33.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/9/z/n/19znwu3pbwfx7upmzjqeti9e47jl68k4v3p9qx4im.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "16\u00A0229 €",
                    "rawPrice": "1136000.0",
                    "priceNote": None,
                    "price": "1\u00A0136\u00A0000 €",
                    "monthlyPrice": 4690,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 224460,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-14eme-75/agency-139318.htm",
                    "contactName": "TERRASSES ET JARDINS RIVE GAUCHE",
                    "imgUrl": "https://v.seloger.com/s/width/150/logos/1/4/v/5/14v5sktt5i2a7h9ahn47lpqvzcb1pic7ap48vfaw5.jpg",
                    "phoneNumber": "0674285361",
                    "email": "true",
                    "agencyLink": "http://www.terrasses-jardins.com",
                },
                "tags": ["3 p", "2 ch", "70 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75015",
                "isExclusive": False,
                "cityLabel": "Paris 15ème",
                "districtLabel": "Dupleix-Motte Picquet",
                "zipCode": "75015",
                "description": "Idéalement situé, au pied du métro Motte Piquet et rue du Commerce, au sein d'une résidence récente de standing, ce bel appar",
                "videoURL": None,
                "virtualVisitURL": "http://tour.previsite.com/p/PGMA/24815341",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-15eme-75/dupleix-motte-picquet/146441595/",
                "optionalCriteria": [],
            },
            {
                "id": 147581675,
                "publicationId": 583874,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 25,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/z/a/m/1zamfw7mcck8gurymejn8eeow9g1yuugv50ekcydc.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/o/b/x/0obxtfsjhil8crd4f8d48bbmc6h48pwxvkk66jvnk.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/z/t/n/0ztnd014rl9bw3dlmw9uikic5x2dbdvmpzigm5p8g.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/5/8/6/058626rax3l9pi70nthog2529prmvfaivz17vwmio.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/d/i/j/0dij2qxjix47cv3m8kgldk0g992alvshumktwrhfk.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "29\u00A0474 €",
                    "rawPrice": "2800000.0",
                    "priceNote": None,
                    "price": "2\u00A0800\u00A0000 €",
                    "monthlyPrice": 11547,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 125736,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-4eme-75/agency-101387.htm",
                    "contactName": "BELLES ADRESSES - Property France",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/1/0/7/y/107yx9rx9rmc6ax5142knusssz41hm0q2hvlxncm5.jpg",
                    "phoneNumber": "0620844912",
                    "email": "true",
                    "agencyLink": "http://www.belles-adresses.com",
                },
                "tags": ["5 p", "3 ch", "95 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75004",
                "isExclusive": True,
                "cityLabel": "Paris 4ème",
                "districtLabel": "Île Saint Louis",
                "zipCode": "75004",
                "description": "A vendre Paris IV: en exclusivité Belles-Adresses, la plus belle adresse au coeur de Paris, sur l'Île Saint-Louis face à la S",
                "videoURL": None,
                "virtualVisitURL": "338528787",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-4eme-75/ile-saint-louis/147581675/",
                "optionalCriteria": [],
            },
            {
                "id": 153299505,
                "publicationId": 30258993,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 13,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/8/g/m/18gmwaa0mrc089r86m0ktofrpxrudcuozkqw9tu1g.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/e/5/c/1e5cni6b1ql7hgfhfyj5zu0enh81qo8cck0bjqq8k.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/v/1/l/0v1l7mk26s1yx4rdiauuu1gbhglfsk78v6s38nmms.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/w/u/b/0wubh3b27bnyo4zatra63xvh9iv1igd5irm4ijot0.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/u/e/o/1ueolk16bzfd1r8dmmuv779oyx6ldd9q4c6mfh104.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "13\u00A0330 €",
                    "rawPrice": "5700000.0",
                    "priceNote": None,
                    "price": "5\u00A0700\u00A0000 €",
                    "monthlyPrice": 23497,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 258993,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-6eme-75/agency-154819.htm",
                    "contactName": "JUNOT FINE PROPERTIES",
                    "imgUrl": "https://v.seloger.com/s/width/97/logos/0/6/y/e/06yeyau6pbok48j0dke7q8o26n8dwuhqe37f5jrzw.jpg",
                    "phoneNumber": "0144497468",
                    "email": "true",
                    "agencyLink": "http://junotfineproperties.com/",
                },
                "tags": ["8 p", "4 ch", "427,6 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75116",
                "isExclusive": True,
                "cityLabel": "Paris 16ème",
                "districtLabel": "Porte Dauphine",
                "zipCode": "75116",
                "description": "Place Victor Hugo, dans un immeuble de grand standing offrant un appartement par palier et sécurisé avec concierge à demeure.",
                "videoURL": None,
                "virtualVisitURL": "https://envisite.net/vtour/fr/tp43ev/frame",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-16eme-75/porte-dauphine/153299505/",
                "optionalCriteria": [],
            },
            {
                "id": 145963599,
                "publicationId": 534193,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 18,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/n/p/0/1np08gajouwgee2g326rw94k3o8y41zhlek4k4e0w.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/l/s/6/1ls6alkcm64upiu37bz4e72m0aihy2uk2cz7m248w.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/1/3/0/21307o13ouay30jhq8j7d9j28iao79dfsmh91nym8.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/5/o/9/25o95p3pv8fvyx4kro2zdf902nl64tby1ovlaeio0.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/0/3/q/203qcyftxob3nbcctomr0h0isay4zq5qijtko3ksg.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "20\u00A0420 €",
                    "rawPrice": "6800000.0",
                    "priceNote": None,
                    "price": "de 3M à 10M €",
                    "monthlyPrice": 28030,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 108728,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-17eme-75/agency-81416.htm",
                    "contactName": "Paris Ouest Sotheby's IR - Paris 17ème",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/0/i/x/z/0ixz2uiul728zvuihqo2d52dly4g3ayo88ofmnz94.jpg",
                    "phoneNumber": "0146222727",
                    "email": "true",
                    "agencyLink": "http://www.parisouest-sothebysrealty.com",
                },
                "tags": ["10 p", "5 ch", "333 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75016",
                "isExclusive": False,
                "cityLabel": "Paris 16ème",
                "districtLabel": "Muette Nord",
                "zipCode": "75016",
                "description": "Paris 16ème - Jardin du Ranelagh. Dans un hôtel particulier Art Déco en pierre de taille entouré d'un jardin de 280 m², super",
                "videoURL": None,
                "virtualVisitURL": "https://www.youtube.com/embed/TldT-2yLLLE",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-16eme-75/muette-nord/145963599/",
                "optionalCriteria": [],
            },
            {
                "id": 146762213,
                "publicationId": 427878,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 16,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/2/5/9/f/259fi1dm92mf6jmo55qy9sg4ncyrafu56n3cxkk5c.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/v/m/2/1vm28agd5ex2sxgho079q8yx52sgl25h974yfrta8.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/5/n/u/05nu7y1cyhek7zgbqs8gc20wujthhaoyjpf8na60w.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/l/r/w/1lrw88tvi5v1e7718djvipej35r5bfxgei8t9cbuo.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/3/6/e/036enx67zeb5t8rdzdzg6ivpn2wi8q5pehlpckwzk.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "14\u00A0987 €",
                    "rawPrice": "5650000.0",
                    "priceNote": None,
                    "price": "5\u00A0650\u00A0000 €",
                    "monthlyPrice": 23291,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 82146,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-16eme-75/agency-68931.htm",
                    "contactName": "PARIS OUEST SOTHEBYS",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/2/a/0/g/2a0gnv4dhlgerh6hyx0vvt5hs31xgjsozz7glhd82.jpg",
                    "phoneNumber": "0140605000",
                    "email": "true",
                    "agencyLink": "http://www.parisouest-sothebysrealty.com",
                },
                "tags": ["9 p", "4 ch", "377 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75116",
                "isExclusive": True,
                "cityLabel": "Paris 16ème",
                "districtLabel": "Muette Nord",
                "zipCode": "75116",
                "description": "Paris 16. Henri Martin. Exclusivité. Dans un immeuble de grand standing, au 2ème étage, bel appartement de 377m². Il se compo",
                "videoURL": None,
                "virtualVisitURL": "https://www.youtube.com/embed/V5cEiKc9f80",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-16eme-75/muette-nord/146762213/",
                "optionalCriteria": [],
            },
            {
                "id": 153468633,
                "publicationId": 30209167,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 7,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/7/g/6/07g6fkjyfzfhl5k1zh0dne6x5czb0apgk7iy28kjk.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/o/g/q/1ogq244hakc55sm7d0yiocv0v9wwtuwk7a87qwk5c.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/c/z/h/1czh6p5htf747vvgtwml5axcjb7r6e5078ml08ow0.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/l/5/6/1l56casw6nbdkvyqyrsvl6z2c0yaourkovhn0rchs.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/j/x/l/0jxl4dtls3lj4k8dt5jjlr92l7zjvanc6bn9xli4g.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 2,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "11\u00A0061 €",
                    "rawPrice": "880000.0",
                    "priceNote": None,
                    "price": "880\u00A0000 €",
                    "monthlyPrice": 3635,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 209167,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-14eme-75/agency-1135876.htm",
                    "contactName": "ADRESSE MAIRIE IMMOBILIER",
                    "imgUrl": "https://v.seloger.com/s/width/150/logos/0/1/a/7/01a7odpoh5cr81vks1h39qhv5q5m6cy0qyn6geb28.jpg",
                    "phoneNumber": "0145451010",
                    "email": "true",
                    "agencyLink": "http://www.ladresse-paris-mairie14.com",
                },
                "tags": ["3 p", "2 ch", "79,56 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75014",
                "isExclusive": True,
                "cityLabel": "Paris 14ème",
                "districtLabel": "Mouton Duvernet",
                "zipCode": "75014",
                "description": "EXCLUSIVITÉ L'ADRESSE - Secteur TRIANGLE D'OR, dans une petite copropriété datée de 1880 bien entretenue, situé au 3ème et au",
                "videoURL": None,
                "virtualVisitURL": "https://my.matterport.com/show/?m=aVcQpZxzNF8",
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat/appartement/paris-14eme-75/mouton-duvernet/153468633.htm",
                "optionalCriteria": [],
            },
            {
                "id": 156547575,
                "publicationId": 651928,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 6,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/x/8/g/0x8gro9ryps7z3i8bgn2x0pjuuych5qkw4or8cwf4.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/f/e/f/1fef8jxfi20xoe9py6htw0o3bxh7ghfakcydu7zts.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/8/5/r/185r3crzauhxotpqqoty2zcagmm5oyznlvw0cxb8g.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/o/g/o/1ogo2fkb20f3y4ds4o89ln6wog3sb83k6ggq2tmw0.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/3/t/x/13txzd6142jxdvxjn6vvv1eddsggy8455f708qecg.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 2,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "17\u00A0273 €",
                    "rawPrice": "190000.0",
                    "priceNote": None,
                    "price": "190\u00A0000 €",
                    "monthlyPrice": 792,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 174358,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-2eme-75/agency-125639.htm",
                    "contactName": "PROPRIOO",
                    "imgUrl": "https://v.seloger.com/s/width/150/logos/0/5/x/y/05xyyjarj60e25iw2kmow9lhm3qknb82il9b17rc0.jpg",
                    "phoneNumber": "01 85 15 55 39",
                    "email": "true",
                    "agencyLink": "http://www.proprioo.fr/?utm_source=seloger&utm_medium=multiposting&utm_campaign=vitrine_agence",
                },
                "tags": ["1 p", "11 m²", "6 etg"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75003",
                "isExclusive": False,
                "cityLabel": "Paris 3ème",
                "districtLabel": "Sainte Avoie",
                "zipCode": "75003",
                "description": "Proprioo, vous propose à la vente ce local, transformable en habitation, de 11 m² localisé Rue Saint-Martin, Paris 3. Rénové ",
                "videoURL": None,
                "virtualVisitURL": "https://www.nodalview.com/PRCPsC5eF1D8jWXEvwzbYjbv",
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat/appartement/paris-3eme-75/sainte-avoie/156547575.htm",
                "optionalCriteria": [],
            },
            {
                "id": 156812541,
                "publicationId": 744265,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 11,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/f/8/6/1f86g5hruty49xn1z9dwv7nr9coku9d075st3x2ww.jpg",
                    "https://v.seloger.com/s/height/400/visuels/0/a/q/5/0aq52r2jezbp8yyltgz5ta44yg4grebd05h9f6bcw.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/e/b/w/1ebw21wdo471k6d2a0kvo06d6rb5sqvybvf4v8t1c.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/g/w/a/1gwaqckp7c219i8debw9syrk6igkcpwgcral59w5c.jpg",
                    "https://v.seloger.com/s/height/400/visuels/1/x/5/s/1x5sg1t6pr2r64hblk5l30u5w17wnwknrhw4fys5b.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 2,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "14\u00A0174 €",
                    "rawPrice": "398000.0",
                    "priceNote": None,
                    "price": "398\u00A0000 €",
                    "monthlyPrice": 1649,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 120549,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-11eme-75/agency-99059.htm",
                    "contactName": "BONJOUR OSCAR BASTILLE SAINT ANTOINE",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/2/2/l/e/22le4id4we8zztkzzznum2nb1xjnadj18qovx7kth.jpg",
                    "phoneNumber": "0140650000",
                    "email": "true",
                    "agencyLink": "http://www.bonjour-oscar.com",
                },
                "tags": ["2 p", "1 ch", "28,08 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75011",
                "isExclusive": True,
                "cityLabel": "Paris 11ème",
                "districtLabel": None,
                "zipCode": "75011",
                "description": "40 rue de Chanzy Paris 11ème. En plein coeur du'Village Faidherbe', à proximité des métro Faidherbe Chaligny, rue des Boulets",
                "videoURL": None,
                "virtualVisitURL": "https://fr.envisite.net/q5gus7",
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat/appartement/paris-11eme-75/156812541.htm",
                "optionalCriteria": [],
            },
            {
                "id": 156870813,
                "publicationId": 651928,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 15,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/l/j/u/0lju2xssxvvr2jwhogt09p1w4m7qoc1nd3sgprg2n.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/3/f/n/23fnyuuiyg0oizn8v507qvc20ekgk2ddzq96xzm00.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/k/t/d/0ktdf3vqztjjqv8luyzn7n5lh4k9gxg0mmoz3j8yo.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/n/s/g/1nsgwtmz9dthvu4oquulaly5xrmpb70xsd2q3l7a8.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/o/f/7/1of7zimjryi0qpysb8fnu770pr6k1wt1trpyxv4tc.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "13\u00A0658 €",
                    "rawPrice": "997000.0",
                    "priceNote": None,
                    "price": "997\u00A0000 €",
                    "monthlyPrice": 4117,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 174358,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-2eme-75/agency-125639.htm",
                    "contactName": "PROPRIOO",
                    "imgUrl": "https://v.seloger.com/s/width/150/logos/0/5/x/y/05xyyjarj60e25iw2kmow9lhm3qknb82il9b17rc0.jpg",
                    "phoneNumber": "01 85 15 55 39",
                    "email": "true",
                    "agencyLink": "http://www.proprioo.fr/?utm_source=seloger&utm_medium=multiposting&utm_campaign=vitrine_agence",
                },
                "tags": ["4 p", "3 ch", "73 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75015",
                "isExclusive": False,
                "cityLabel": "Paris 15ème",
                "districtLabel": "Pasteur Montparnasse",
                "zipCode": "75015",
                "description": "Proprioo, l'agence nouvelle génération, vous propose à la vente ce très bel appartement familial de 4 pièces de 73.26 m² carr",
                "videoURL": "https://www.nodalview.com/AJLVm6Mdwkwdskwh5qc95PoK",
                "virtualVisitURL": "https://www.nodalview.com/AJLVm6Mdwkwdskwh5qc95PoK",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-15eme-75/pasteur-montparnasse/156870813/",
                "optionalCriteria": [],
            },
            {
                "id": 156948053,
                "publicationId": 30258336,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 6,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/o/8/j/0o8jhjttvad9so75oxw7x5hc75ewzu06zothvf73k.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/u/r/t/1urtnis1khyad28mqmylqca0gdi19kugnd044kmuo.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/k/a/r/1kargjgl9eqkidskc98zlfv9d38m7viug1hnf6dgw.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/5/a/r/05arndwcp847gh5a6ro1wdxzn9thi81vihj0lwtyo.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/q/v/d/1qvdk1dw73xolaio22b2yrutt94xqduv564v4i3zk.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "16\u00A0048 €",
                    "rawPrice": "995000.0",
                    "priceNote": None,
                    "price": "995\u00A0000 €",
                    "monthlyPrice": 4109,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 258336,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-2eme-75/agency-154507.htm",
                    "contactName": "HOSMAN",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/2/9/f/w/29fwyxh91ulneuv9nj9zd5ilxa2psge50pv3b46s8.jpg",
                    "phoneNumber": "06 66 13 75 00",
                    "email": "true",
                    "agencyLink": "http://www.hosman.co/",
                },
                "tags": ["2 p", "1 ch", "62 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75006",
                "isExclusive": False,
                "cityLabel": "Paris 6ème",
                "districtLabel": "Saint Germain des Prés",
                "zipCode": "75006",
                "description": "Hosman vous propose à la vente ce beau 2 pièces de 62\u00A0m² dans un immeuble sécurisé (gardien) du 17ème, ouvrant sur une cour i",
                "videoURL": None,
                "virtualVisitURL": "https://my.matterport.com/show/?m=ReacYigqNzK",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-6eme-75/saint-germain-des-pres/156948053/",
                "optionalCriteria": [],
            },
            {
                "id": 156948059,
                "publicationId": 30258336,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 7,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/e/t/r/1etrff9lvdfenpq3nxpe9ggbs2qxls6lhz5cb4pf4.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/3/8/5/03855y7h2ezdwf14cwijqcibczq7mnt3jzflugvcg.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/0/e/l/20elc0qhpmdacmc72t4rayoiawwd6q8o8ve5dcnu8.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/a/8/n/0a8n4jwtlvdgb572x7s9peddjeroaxaciouar833k.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/0/d/c/00dcaa2jl3zqyqjds25eebdwq63tmh11niacewvcg.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "17\u00A0431 €",
                    "rawPrice": "889000.0",
                    "priceNote": None,
                    "price": "889\u00A0000 €",
                    "monthlyPrice": 3672,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 258336,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-2eme-75/agency-154507.htm",
                    "contactName": "HOSMAN",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/2/9/f/w/29fwyxh91ulneuv9nj9zd5ilxa2psge50pv3b46s8.jpg",
                    "phoneNumber": "06 66 13 75 00",
                    "email": "true",
                    "agencyLink": "http://www.hosman.co/",
                },
                "tags": ["2 p", "1 ch", "51 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75006",
                "isExclusive": False,
                "cityLabel": "Paris 6ème",
                "districtLabel": "Saint Germain des Prés",
                "zipCode": "75006",
                "description": "Hosman vous propose à la vente ce beau 2 pièces de 51\u00A0m² dans un immeuble sécurisé (gardien) du 17ème, ouvrant sur une cour i",
                "videoURL": None,
                "virtualVisitURL": "https://my.matterport.com/show/?m=VVnd1h5SsMD",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-6eme-75/saint-germain-des-pres/156948059/",
                "optionalCriteria": [],
            },
            {
                "id": 156948063,
                "publicationId": 30258336,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 13,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/s/9/r/1s9r4zpn3wlisohbbxpm5zut7oex0oij653xmvr1s.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/4/k/s/24kshz3pyidt1u6tdcyq6l2f33zvufuezii2xpsc0.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/8/y/e/18ye2d55x3mznsssqxhtfhkhdn5ar1imuvdsz246o.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/e/8/l/1e8luhj4na95liocsdid0poe3jsvbgi7eq310gf5c.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/a/a/j/0aaj67q6zoi3vey3g4ee1b9berjuv3d7alf5pw69c.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 2,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "10\u00A0970 €",
                    "rawPrice": "362000.0",
                    "priceNote": None,
                    "price": "362\u00A0000 €",
                    "monthlyPrice": 1501,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 258336,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-2eme-75/agency-154507.htm",
                    "contactName": "HOSMAN",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/2/9/f/w/29fwyxh91ulneuv9nj9zd5ilxa2psge50pv3b46s8.jpg",
                    "phoneNumber": "06 29 16 93 75",
                    "email": "true",
                    "agencyLink": "http://www.hosman.co/",
                },
                "tags": ["1 p", "33 m²", "1 asc"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75020",
                "isExclusive": False,
                "cityLabel": "Paris 20ème",
                "districtLabel": "Télégraphe-Pelleport Saint Fargeau",
                "zipCode": "75020",
                "description": "Hosman vous propose à la vente ce ravissant studio d'une surface de 32,55 m² carrez, situé rue Olivier Métra, au coeur du qua",
                "videoURL": None,
                "virtualVisitURL": "https://my.matterport.com/show/?m=82PjaUsRuwr",
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat/appartement/paris-20eme-75/telegraphe-pelleport-saint-fargeau/156948063.htm",
                "optionalCriteria": [],
            },
            {
                "id": 156968201,
                "publicationId": 780502,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 11,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/0/z/s/00zslvqbsx47w5lq2t1pnilins9pf55mtncwdw2yo.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/1/g/i/01gibilrjdkm8v13zb5t97enlbq0pito2euw5xpfk.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/i/u/t/0iuti5ggo33ntsebaftcvncdut8ia2jhf5v0wyp6o.jpg",
                    "https://v.seloger.com/s/height/400/visuels/0/i/2/b/0i2bgxmqb3chmvn9gefs4lxbaarwprun8xvhuickf.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/3/7/0/1370q0rng1u5jy43p5vrh2o1ppph2x2r5iekan8cg.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "11\u00A0511 €",
                    "rawPrice": "1120000.0",
                    "priceNote": None,
                    "price": "1\u00A0120\u00A0000 €",
                    "monthlyPrice": 4624,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 264949,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-11eme-75/agency-157037.htm",
                    "contactName": "BONJOUR OSCAR CHARONNE",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/1/i/m/y/1imy62k8o1wr3txi64tsd9uzlh6g4s3zitnswsgu0.jpg",
                    "phoneNumber": "0145670000",
                    "email": "true",
                    "agencyLink": "http://www.bonjour-oscar.com/",
                },
                "tags": ["4 p", "3 ch", "97,3 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75011",
                "isExclusive": True,
                "cityLabel": "Paris 11ème",
                "districtLabel": "Nation-Alexandre Dumas",
                "zipCode": "75011",
                "description": "L'agence Bonjour-Oscar Charonne vous présente en exclusivité un appartement de 102m², 4 pièces avec loggia fermée, situé au 9",
                "videoURL": None,
                "virtualVisitURL": "https://envisite.net/vtour/fr/8fpnqm",
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat-de-prestige/appartement/paris-11eme-75/nation-alexandre-dumas/156968201.htm",
                "optionalCriteria": [],
            },
            {
                "id": 156975733,
                "publicationId": 549283,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 10,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/k/3/u/0k3uvkhuoyluwobcqhoiodno1ejx4rsokg11zk2zi.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/1/0/7/2107gbrjaod18uftz1va1qnnry4xoio9ugoyf8ufz.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/k/e/0/1ke0fjop7b46d6jigdg2f28uf47ut6l59uk81hkin.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/k/h/m/0khmrpovgy9mjjo4bv0zll0f1eqs5bfi0gythhq1q.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/2/7/x/127xdbms1r42r48qwk68ktyrj8mbujm77ktwz9e72.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 2,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "10\u00A0583 €",
                    "rawPrice": "635000.0",
                    "priceNote": None,
                    "price": "635\u00A0000 €",
                    "monthlyPrice": 2626,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 113840,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-17eme-75/agency-86441.htm",
                    "contactName": "building partners",
                    "imgUrl": "https://v.seloger.com/s/width/150/logos/0/k/1/m/0k1mzc784eo4vquon78r58hxoyh4jehc0silpt2ty.jpg",
                    "phoneNumber": "0145720000",
                    "email": "true",
                    "agencyLink": "http://www.bpimmo.com",
                },
                "tags": ["3 p", "2 ch", "60 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75017",
                "isExclusive": False,
                "cityLabel": "Paris 17ème",
                "districtLabel": "Pereire-Malesherbes",
                "zipCode": "75017",
                "description": "Proche boulevard Pereire. Atelier d'artiste 2 pièces de 53 m² au rez-de-chaussée et 1er étage dans un immeuble ancien de très",
                "videoURL": None,
                "virtualVisitURL": "https://my.matterport.com/show/?m=bbrWZ2mKict",
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat/appartement/paris-17eme-75/pereire-malesherbes/156975733.htm",
                "optionalCriteria": [],
            },
            {
                "id": 157282849,
                "publicationId": 295322,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 5,
                "photos": [
                    "https://v.seloger.com/s/width/399/visuels/0/8/y/9/08y9xb9nzhq0ift5q6q8r3894lw793tjcpxhnbqkz.jpg",
                    "https://v.seloger.com/s/width/399/visuels/2/8/u/m/28umb19387t5onezrqdpwocfpmky3z6766m6xalw3.jpg",
                    "https://v.seloger.com/s/width/399/visuels/0/3/e/i/03eix181ewzzk1kl6yow5sa6vyuc5gqxhx9zl98wj.jpg",
                    "https://v.seloger.com/s/width/399/visuels/1/8/c/m/18cmltqoknjt61vv0lmr3z9w68hk4jrltsp2wuzbn.jpg",
                    "https://v.seloger.com/s/width/399/visuels/1/0/q/l/10ql8uwromgdrk8lb5agpnhaj3qjnne15ej26efyr.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "15\u00A0312 €",
                    "rawPrice": "490000.0",
                    "priceNote": None,
                    "price": "490\u00A0000 €",
                    "monthlyPrice": 2028,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 58847,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-16eme-75/agency-62867.htm",
                    "contactName": "BRETEUIL IMMOBILIER",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/0/3/m/w/03mwvwiuwm1k8tp4hhnj0nauwllqyfjenj01eyus8.jpg",
                    "phoneNumber": "0140670000",
                    "email": "true",
                    "agencyLink": "http://www.breteuilimmo.com",
                },
                "tags": ["1 p", "32 m²", "1 asc"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75016",
                "isExclusive": True,
                "cityLabel": "Paris 16ème",
                "districtLabel": "Chaillot",
                "zipCode": "75016",
                "description": "Immeuble 1980 de standing, résidence sécurisée avec gardiennage jour et nuit à proximité de la Place Iéna, vaste studio de 32",
                "videoURL": "https://www.youtube.com/watch?v=iXOX9PmWjDc",
                "virtualVisitURL": None,
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-16eme-75/chaillot/157282849/",
                "optionalCriteria": [],
            },
            {
                "id": 157426287,
                "publicationId": 651928,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 13,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/s/f/a/1sfa5f81ih8rm26up2hpti4dcmzhsobvtz9qb8lr4.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/x/4/d/0x4dfwudj73kg17z136lxlr64fsoiix9x1ssojmzk.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/n/z/9/1nz9gpty37a5105vuganca6g0dtgxpuvhxkyo9bmo.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/k/2/6/0k26dvfdib0gzjyzhsrq6o8rftxe48869xvgcmihs.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/5/m/1/25m1evgt9s5dnqdxnartcbkillrtsfprlxqf7v2u8.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "12\u00A0917 €",
                    "rawPrice": "1395000.0",
                    "priceNote": None,
                    "price": "1\u00A0395\u00A0000 €",
                    "monthlyPrice": 5757,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 174358,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-2eme-75/agency-125639.htm",
                    "contactName": "PROPRIOO",
                    "imgUrl": "https://v.seloger.com/s/width/150/logos/0/5/x/y/05xyyjarj60e25iw2kmow9lhm3qknb82il9b17rc0.jpg",
                    "phoneNumber": "01 85 15 55 39",
                    "email": "true",
                    "agencyLink": "http://www.proprioo.fr/?utm_source=seloger&utm_medium=multiposting&utm_campaign=vitrine_agence",
                },
                "tags": ["6 p", "4 ch", "108 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75020",
                "isExclusive": False,
                "cityLabel": "Paris 20ème",
                "districtLabel": "Plaine",
                "zipCode": "75020",
                "description": "Proprioo, l'agence nouvelle génération, vous propose à la vente cet appartement 6 pièces de 108 m² avec 33 m² de terrasse au ",
                "videoURL": None,
                "virtualVisitURL": "https://www.nodalview.com/S46VU7uzq8s9BdCLWy34qynS",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-20eme-75/plaine/157426287/",
                "optionalCriteria": [],
            },
            {
                "id": 156169823,
                "publicationId": 30405758,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 11,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/5/3/d/053d3r3zqs2v436zvj8gfqgw6bzwzbe9lt4djsfva.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/4/3/1/1431bkzq4slvvgoqhxd84pf2s3znevfnzd744tv12.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/r/d/d/0rddzjn8yglwmhl0itnktzifsuokown6t1qji7y3a.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/x/g/j/1xgj3735f9ape5b7gvop55ozqsm5kcuhxwd6omuza.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/2/d/j/12djibjajt84a9cn8gyy1sk75iqbxrmjooa0a9zkm.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 2,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "15\u00A0858 €",
                    "rawPrice": "546000.0",
                    "priceNote": None,
                    "price": "546\u00A0000 €",
                    "monthlyPrice": 2259,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 405758,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-7eme-75/agency-656356.htm",
                    "contactName": "JUNOT 7e",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/1/1/5/k/115kugkgshpuuwshs1d9yhv5xwmqp2kvcdndrjozm.jpg",
                    "phoneNumber": "0142736230",
                    "email": "true",
                    "agencyLink": None,
                },
                "tags": ["2 p", "1 ch", "34,43 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75007",
                "isExclusive": False,
                "cityLabel": "Paris 7ème",
                "districtLabel": "Gros Caillou",
                "zipCode": "75007",
                "description": "Au sein d'une copropriété avec poutres apparentes datant de 1860, bel appartement de 34,42m² loi Carrez au sixième et dernier",
                "videoURL": None,
                "virtualVisitURL": "https://envisite.net/vtour/fr/ftojl7/frame",
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat/appartement/paris-7eme-75/gros-caillou/156169823.htm",
                "optionalCriteria": [],
            },
            {
                "id": 156269965,
                "publicationId": 30317246,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 4,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/t/m/1/0tm17125kx69vzwcfl1yxypdakf685csldjpi8rnk.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/g/w/x/0gwxyyucnm3vvcnglgm7axqd430maqeiqiip9xb7k.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/y/a/c/0yac3r81e1ns0475y5t5w4kt3w08i7cr986p5kc8w.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/i/g/e/1igepsq2ssdoszqyhgky4qm5vfah96cse50w459mo.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 2,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "10\u00A0744 €",
                    "rawPrice": "419000.0",
                    "priceNote": None,
                    "price": "419\u00A0000 €",
                    "monthlyPrice": 1736,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 317246,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-19eme-75/agency-1129215.htm",
                    "contactName": "SCOOP IMMOBILIER",
                    "imgUrl": "https://v.seloger.com/s/width/148/logos/1/u/h/q/1uhqxke4bg2eih1cr2vgf38mfw74ddcu1kdarxgvi.jpg",
                    "phoneNumber": "0177370770",
                    "email": "true",
                    "agencyLink": "http://www.ladresse-paris-jourdain.com",
                },
                "tags": ["2 p", "1 ch", "39 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75019",
                "isExclusive": True,
                "cityLabel": "Paris 19ème",
                "districtLabel": "Secrétan",
                "zipCode": "75019",
                "description": "Paris 19: Marché Secrétan: Coup de Coeur, rare à la vente.. A deux pas des Buttes Chaumont dans un immeuble très bien tenue d",
                "videoURL": None,
                "virtualVisitURL": "l",
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat/appartement/paris-19eme-75/secretan/156269965.htm",
                "optionalCriteria": [],
            },
            {
                "id": 157126331,
                "publicationId": 312442,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 9,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/s/f/i/0sfi7g01bvpcyzzoue04eibsqbxte5t0qebozivj4.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/6/k/2/26k26hmu0jhr3vajfdrqj22nk6ui9p9t686dnw36o.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/l/n/6/1ln6nkya4iurtswxee1ensuf0w14hpy64oof0dwrk.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/0/x/u/10xueoswaoohwrv4f2zudusosfhx98pnhzdda9li8.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/3/n/i/23ni350qg21o3vrj8epmf53c5621wzxrlkxmsk0f4.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "17\u00A0234 €",
                    "rawPrice": "1620000.0",
                    "priceNote": None,
                    "price": "1\u00A0620\u00A0000 €",
                    "monthlyPrice": 6685,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 61382,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-6eme-75/agency-63525.htm",
                    "contactName": "BRETEUIL IMMOBILIER",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/0/3/m/w/03mwvwiuwm1k8tp4hhnj0nauwllqyfjenj01eyus8.jpg",
                    "phoneNumber": "0142848500",
                    "email": "true",
                    "agencyLink": "http://www.breteuilimmo.com",
                },
                "tags": ["4 p", "2 ch", "94 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75006",
                "isExclusive": False,
                "cityLabel": "Paris 6ème",
                "districtLabel": "Saint Germain des Prés",
                "zipCode": "75006",
                "description": "Saint GERMAIN DES PRÈS - Immeuble fin 18ÈME aux parties communes soignées, appartement en duplex de 93,44m² loi Carrez (97,08",
                "videoURL": "https://www.youtube.com/watch?v=iXOX9PmWjDc",
                "virtualVisitURL": None,
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-6eme-75/saint-germain-des-pres/157126331/",
                "optionalCriteria": [],
            },
            {
                "id": 157514299,
                "publicationId": 427878,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 11,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/6/i/g/16igrhzr6em7onoihnozrzez86hpub2akjk26s1ds.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/4/s/i/14si98kmsrbyz70tssgqqa6pcl4kcxzwmtt5wzzsw.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/q/f/9/0qf9jq8uyxpo9ez5o024qg4xgvmmfw2z10jwijocg.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/5/2/h/152hmv9znj168oprr355cf0bt62ithptpbobd7sao.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/6/r/x/16rxo162xzdjk163nx3j9u3f7zvnwa9noexb8hds0.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "23\u00A0636 €",
                    "rawPrice": "2600000.0",
                    "priceNote": None,
                    "price": "2\u00A0600\u00A0000 €",
                    "monthlyPrice": 10723,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 82146,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-16eme-75/agency-68931.htm",
                    "contactName": "PARIS OUEST SOTHEBYS",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/2/a/0/g/2a0gnv4dhlgerh6hyx0vvt5hs31xgjsozz7glhd82.jpg",
                    "phoneNumber": "0140605000",
                    "email": "true",
                    "agencyLink": "http://www.parisouest-sothebysrealty.com",
                },
                "tags": ["3 p", "2 ch", "110 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75016",
                "isExclusive": False,
                "cityLabel": "Paris 16ème",
                "districtLabel": "Chaillot",
                "zipCode": "75016",
                "description": "Paris 16ème -Trocadéro. Dans un immeuble de très bon standing, au 2ème étage avec ascenseur, bel appartement de 110 m² (Loi C",
                "videoURL": None,
                "virtualVisitURL": "https://www.youtube.com/embed/oWOuRzpLZzk",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-16eme-75/chaillot/157514299/",
                "optionalCriteria": [],
            },
            {
                "id": 157522681,
                "publicationId": 295322,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 8,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/1/y/4/o/1y4otbeyhh564lmgbfidskyapa2snh481d7djqrtg.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/h/6/l/1h6lw627ahzrciugfcy251cvco8xfq18jmu6fwtw4.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/j/8/3/0j83dvgs339bxw1clfya0aszka3ha145y7rrsf044.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/m/b/a/0mbaqy7dr9ok95qgxlv7asv60zbuh8kd9vtqpwf9w.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/i/7/h/0i7hg991vk9afu943q5g4k22rcotg05id3l6bpkd0.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "12\u00A0570 €",
                    "rawPrice": "2250000.0",
                    "priceNote": None,
                    "price": "2\u00A0250\u00A0000 €",
                    "monthlyPrice": 9281,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 58847,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-16eme-75/agency-62867.htm",
                    "contactName": "BRETEUIL IMMOBILIER",
                    "imgUrl": "https://v.seloger.com/s/width/75/logos/0/3/m/w/03mwvwiuwm1k8tp4hhnj0nauwllqyfjenj01eyus8.jpg",
                    "phoneNumber": "0140670000",
                    "email": "true",
                    "agencyLink": "http://www.breteuilimmo.com",
                },
                "tags": ["6 p", "4 ch", "179 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75016",
                "isExclusive": True,
                "cityLabel": "Paris 16ème",
                "districtLabel": "Porte Dauphine",
                "zipCode": "75016",
                "description": "Très bel immeuble pierre de taille, appartement familial entièrement refait, situé au 5ème et dernier étage avec ascenseur, b",
                "videoURL": "https://www.youtube.com/watch?v=iXOX9PmWjDc",
                "virtualVisitURL": None,
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-16eme-75/porte-dauphine/157522681/",
                "optionalCriteria": [],
            },
            {
                "id": 150962951,
                "publicationId": 720813,
                "highlightingLevel": 3,
                "businessUnit": 5,
                "photosQty": 8,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/u/x/x/0uxx7v9trpvjtbob2o9a6j2ilzainwkseyzg0cqvy.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/v/3/v/0v3vpv4qdu25x0c691qrdix6vap4f51vuojgl3bq6.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/b/v/f/1bvf3d7inpcx46rwb1gfo5686458qpemewkjv75lq.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/p/d/x/1pdxmdhm6h305l5uoiam7nvb8abzs3y4kt27go07y.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/l/d/l/1ldlb12azo8x0a34rzllzw3md3f7vl24z1vbq204e.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 8,
                "nature": 3,
                "pricing": {
                    "squareMeterPrice": "14\u00A0167 €",
                    "rawPrice": "1360000.0",
                    "priceNote": None,
                    "price": "1\u00A0360\u00A0000 €",
                    "monthlyPrice": 5613,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 224460,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-14eme-75/agency-139318.htm",
                    "contactName": "TERRASSES ET JARDINS RIVE GAUCHE",
                    "imgUrl": "https://v.seloger.com/s/width/150/logos/1/4/v/5/14v5sktt5i2a7h9ahn47lpqvzcb1pic7ap48vfaw5.jpg",
                    "phoneNumber": "0612996011",
                    "email": "true",
                    "agencyLink": "http://www.terrasses-jardins.com",
                },
                "tags": ["3 p", "2 ch", "96 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75013",
                "isExclusive": False,
                "cityLabel": "Paris 13ème",
                "districtLabel": "Olympiades-Choisy",
                "zipCode": "75013",
                "description": "Au sein d'une copropriété très bien entretenue, dépaysement garanti dans cet insoupçonnable et rare appartement en dernier ét",
                "videoURL": None,
                "virtualVisitURL": "http://tour.previsite.com/p/PGMA/26983721",
                "housingBatch": [],
                "classifiedURL": "https://www.bellesdemeures.com/annonces/vente/appartement-luxe/paris-13eme-75/olympiades-choisy/150962951/",
                "optionalCriteria": [],
            },
            {
                "id": 152872403,
                "publicationId": 503909,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 18,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/z/o/8/0zo8u5azjkdmz4dp2g5z072lfhsjw57qmpxadl8n4.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/0/l/s/10ls61uim4s8w5kaw9hbz7ebe5unbdichnfq45u68.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/a/4/e/2a4egovvdqkyi8e0utajo9gqy5etrkarwbxgmpg5c.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/a/u/y/1auycogk1mj2mbrkeqiiq39shgmk7fdua9vxokhz4.jpg",
                    "https://v.seloger.com/s/width/400/visuels/2/5/4/8/2548y5fxmmapb2qx6vl3b9isrbd7i372xpqsrwmbk.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 2,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "8\u00A0817 €",
                    "rawPrice": "723000.0",
                    "priceNote": None,
                    "price": "723\u00A0000 €",
                    "monthlyPrice": 2988,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 102059,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/paris-13eme-75/agency-76167.htm",
                    "contactName": "OPTION 13",
                    "imgUrl": "https://v.seloger.com/s/width/148/logos/1/9/x/e/19xebv6ejb9b72texa6cvs5zol56rrfa80llchunb.jpg",
                    "phoneNumber": "0182838161",
                    "email": "true",
                    "agencyLink": "http://www.option13.fr",
                },
                "tags": ["4 p", "1 ch", "82 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75013",
                "isExclusive": True,
                "cityLabel": "Paris 13ème",
                "districtLabel": "Salpêtrière-Austerlitz",
                "zipCode": "75013",
                "description": "Paris XIII - SECTEUR DUNOIS Dans un bel immeuble récent, venez découvrir un très beau 4 pièces, bien agencé, composé d'une en",
                "videoURL": None,
                "virtualVisitURL": "https://my.matterport.com/show/?m=9ucJj2RZpHU&lang=fr",
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat/appartement/paris-13eme-75/salpetriere-austerlitz/152872403.htm",
                "optionalCriteria": [],
            },
            {
                "id": 155115449,
                "publicationId": 30094052,
                "highlightingLevel": 3,
                "businessUnit": 1,
                "photosQty": 6,
                "photos": [
                    "https://v.seloger.com/s/width/400/visuels/0/3/j/9/03j9gjffdtmf161mqy8io8io4o2xoypanmoa32f40.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/k/7/u/0k7uy3hu5dgqf4h0lxrmjsxj5hzfea0d9sui4tmo0.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/e/7/6/1e76o1o64qpyxrr5joczmulieolw1bymps9531wxs.jpg",
                    "https://v.seloger.com/s/width/400/visuels/1/w/o/x/1woxfch4ktgi0pohdgfuki3aj4o6d1r8qmo7rludc.jpg",
                    "https://v.seloger.com/s/width/400/visuels/0/l/n/e/0lneanylgxbl6p74xyy6f8i5j99sce4f2a8gtsu0w.jpg",
                ],
                "estateType": "Appartement",
                "transactionType": 2,
                "nature": 1,
                "pricing": {
                    "squareMeterPrice": "11\u00A0822 €",
                    "rawPrice": "715000.0",
                    "priceNote": None,
                    "price": "715\u00A0000 €",
                    "monthlyPrice": 2955,
                    "lifetime": False,
                    "loanServiceUrl": "https://e-immobilier.credit-agricole.fr/simulca/?ORI=selogercampagne&xtor=AL-2-[partenariat]-[Seloger]-[lien_a_partir_prix]-[pdl]",
                },
                "contact": {
                    "agencyId": 94052,
                    "agencyPage": "https://www.seloger.com/professionnels/agences-immobilieres/boulogne-billancourt-92/agency-73196.htm",
                    "contactName": "ACONIM",
                    "imgUrl": "https://v.seloger.com/s/width/105/logos/1/a/g/o/1agohxmzdjtd9ngk11h4i5phtfcxpzo6wfrkxcney.jpg",
                    "phoneNumber": "0680572295",
                    "email": "true",
                    "agencyLink": None,
                },
                "tags": ["2 p", "1 ch", "60,48 m²"],
                "serviceUrl": "http://wwww.seloger.com/credit-immobilier.htm?cp=75008",
                "isExclusive": True,
                "cityLabel": "Paris 8ème",
                "districtLabel": "Europe",
                "zipCode": "75008",
                "description": "TURIN/BATIGNOLLES - Dans un immeuble bourgeois au 2ème étage avec ascenseur, l'agence Aconim vous propose un charmant 2 pièce",
                "videoURL": "https://my.matterport.com/show/?m=koPrHXV5rfk",
                "virtualVisitURL": None,
                "housingBatch": [],
                "classifiedURL": "https://www.seloger.com/annonces/achat/appartement/paris-8eme-75/europe/155115449.htm",
                "optionalCriteria": [],
            },
        ],
        "enlargementResult": None,
    },
    "querystring": "projects=2,5&types=1,2&natures=1,2,4&places=[{cp:75}]&surface=2/NaN&enterprise=0&qsVersion=1.0",
    "metadata": {
        "search": {
            "nbresults": 9381,
            "typedetransaction": ["vente", "viager"],
            "nbpieces": None,
            "typedebien": ["Appartement", "Maison/Villa"],
            "pays": "FR",
            "nbchambres": None,
            "budget": {"min": None, "max": None},
            "surface": {"min": "2", "max": None},
            "surface_terrain": {"min": None, "max": None},
            "etage": {"min": "0", "max": None},
            "tri": {"criteria": "Sélection"},
            "chauffage": [
                {"name": "individuel", "value": False},
                {"name": "central", "value": False},
                {"name": "electrique", "value": False},
                {"name": "gaz", "value": False},
                {"name": "fuel", "value": False},
                {"name": "radiateur", "value": False},
                {"name": "sol", "value": False},
            ],
            "cuisine": [
                {"name": "cuisine separee", "value": False},
                {"name": "cuisine americaine", "value": False},
                {"name": "coin cuisine", "value": False},
                {"name": "cuisine equipee", "value": False},
            ],
            "naturebien": [
                {"name": "investissement", "value": False},
                {"name": "viager", "value": True},
                {"name": "courte duree", "value": False},
                {"name": "meuble", "value": False},
                {"name": "nonmeuble", "value": False},
                {"name": "ancien", "value": True},
                {"name": "neuf", "value": True},
                {"name": "construire", "value": True},
                {"name": "luxe", "value": False},
            ],
            "supplement": [
                {"name": "avecPhoto", "value": False},
                {"name": "visiteVirtuelle", "value": False},
                {"name": "evolutionPrix", "value": False},
                {"name": "exclusivites", "value": False},
                {"name": "professionnels", "value": True},
                {"name": "avecVideo", "value": False},
            ],
            "amenagements": [
                {"name": "salleAmanger", "value": False},
                {"name": "sejour", "value": False},
                {"name": "toiletteSeparee", "value": False},
                {"name": "salleDeBain", "value": False},
                {"name": "salleDEau", "value": False},
                {"name": "entreeSepare", "value": False},
            ],
            "commodites": [
                {"name": "terrasse", "value": False},
                {"name": "balcon", "value": False},
                {"name": "cheminee", "value": False},
                {"name": "parquet", "value": False},
                {"name": "climatisation", "value": False},
                {"name": "alarme", "value": False},
                {"name": "placards", "value": False},
                {"name": "dernier etage", "value": False},
                {"name": "ascenseur", "value": False},
                {"name": "parking ouvert", "value": False},
                {"name": "box", "value": False},
                {"name": "cave", "value": False},
                {"name": "piscine", "value": False},
                {"name": "interphone", "value": False},
                {"name": "digicode", "value": False},
                {"name": "gardien", "value": False},
                {"name": "handicape", "value": False},
            ],
            "situation": [
                {"name": "sud", "value": False},
                {"name": "belleVue", "value": False},
                {"name": "sansVisAVis", "value": False},
            ],
            "localites": [{"type": "departement", "value": ["75"]}],
        },
        "zipCodes": [],
        "geoDpCodes": ["75"],
        "summary": ["Achat", "Paris", "Appartement"],
    },
}
